### ISSUE TITLE
Decrypt with private key in c++ failed

### ISSUE THREAD

**Issue by AdoBeatTheWorld** [travist/jsencrypt#156]
installed with npm, version:2.3.0
`
thisKeyPair = new JSEncrypt({default_key_size: 1024,log:true});

thisKeyPair.encrypt(plaintext)
`

and then send private key and content to cpp, decypt in cpp side:

`
 RSA *rsa = RSA_new();
        BIO *keybio;
        keybio = BIO_new_mem_buf((unsigned char *)key.c_str(), -1);
        rsa = PEM_read_bio_RSAPrivateKey(keybio, &rsa, NULL, NULL);
        int len = RSA_size(rsa);
        out.resize(len);
        int ret = RSA_private_decrypt(content.size(), (const unsigned char*)content.c_str(), &out[0], rsa, RSA_PKCS1_PADDING);
        if (ret <= 0)
        {
            out.resize(0);
            cout << "Failure." << endl;
            unsigned long errorcode = ERR_peek_last_error();
            cout << "Error Code:" << errorcode << endl;
            char errmsg[1024] = {0};
            char *tmp = NULL;
            tmp = ERR_error_string(errorcode,errmsg);
            cout << errmsg << endl;
        }else
        {
            string s(out.begin(),out.end());
            cout << "Success : " << s << endl;
        }

        BIO_free_all(keybio);
        RSA_free(rsa);
`
it failed as below:
> Failure.
> Error Code:67522668
> error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len
and i digged a little on both side.
on js side:
the raw messge is 16-length string, after encrypt it is 128-length, and after dopublic and tostring(16), it was 256-length, at the end after b64 it was 172-length.
on the cpp side:
i recieved 172-length, surely it will fail because it is more than 128.
and i did b64 reverse to 256,
after that i don't know what to do to make it decrypted to the 128-length content.

so the problem is how can i decrypt the raw message in the cpp with openssl completely..

**Comment by AdoBeatTheWorld** [comment]
Problem solved by myself.

**Comment by wenjoy** [comment]
@adoontheway  can u share how do u solve it? I also encountered this issue.

**Comment by adoontheway** [comment]
@wenjoy 

it is the js side problem,you need to make a modifications refer to my [note](https://adoontheway.github.io/2019/07/13/rsafirstresult/)

**Comment by wenjoy** [comment]
Thanks @adoontheway. Nice blog 👍 

Though I solved my issue by decoding the result with base64. Coz the `jsencrypt` encoded the cipher as base64.
