### ISSUE TITLE
Private Key encryption / Public Key decryption

### ISSUE THREAD

**Issue by michaeldisaro** [travist/jsencrypt#187]
I've seen this repository is abandoned, I forked it to add the private key encryption for non-repudiation/authentication that I needed and maybe I will maintain it a bit. As @travist said this is a sort of "collage" to manage PEM keys using other party libraries, I will just clean a bit the examples and be sure that it works and can be decrypted by other frameworks such as .NET Core / BouncyCastles.

**Comment by hamming** [comment]
@travist 
Hi travist, does it support decrypt with publickKey?

Thanks!

**Comment by michaeldisaro** [comment]
> @travist
> Hi travist, does it support decrypt with publickKey?
> 
> Thanks!

My fork does.
