### ISSUE TITLE
ReferenceError: JSENCRYPT_VERSION is not defined

### ISSUE THREAD

**Issue by anrananran** [travist/jsencrypt#193]
after version update,  the main attr change to 'lib/index.js' in package.json, this error occured

**Comment by weibalangzi** [comment]
same question as you

> after version update, the main attr change to 'lib/index.js' in package.json, this error occured

**Comment by Pandorapa** [comment]
> after version update, the main attr change to 'lib/index.js' in package.json, this error occured
Uncaught ReferenceError: JSENCRYPT_VERSION is not defined。
yes,me too

**Comment by holgor** [comment]
The same problem occurred after my last building on Jenkins today.

**Comment by shisongsongya** [comment]
same question as you

**Comment by may-creator** [comment]
same question as you

**Comment by ns265422** [comment]
same question as you

**Comment by fwfmiao** [comment]
same question as you

**Comment by America-first-melon** [comment]
same question as you

**Comment by Pandorapa** [comment]
The same problem puzzled me for a day, but using the fixed version still didn't solve the proble,m,n

**Comment by varunraghu3112** [comment]
Same problem for me as well!

**Comment by hebertlima** [comment]
same here too `Uncaught ReferenceError: JSENCRYPT_VERSION is not defined`

**Comment by lararium** [comment]
Same problem for me as well

**Comment by zerlous** [comment]
The same problem.

**Comment by anrananran** [comment]
just replace `import JSEncrypt from 'jsencrypt'` with `import JSEncrypt from 'jsencrypt/bin/jsencrypt.min.js'`

**Comment by panqinqin** [comment]
The same problem.

**Comment by Alfxjx** [comment]
is it a recent error? the same project which has this package didn't have error month ago

**Comment by monicaxun** [comment]
I think it's a recent error.
I encountered the error just today. It's still OK three days ago.

**Comment by varunraghu3112** [comment]
> I think it's a recent error.
> I encountered the error just today. It's still OK three days ago.

Yes it occurring from yesterday !

**Comment by surele** [comment]
same question as you

**Comment by tlongzou** [comment]
> just replace `import JSEncrypt from 'jsencrypt'` with `import JSEncrypt from 'jsencrypt/bin/jsencrypt.min.js'`

@travist maybe we can change main value from `"lib/index.js"` to `"bin/jsencrypt.min.js"` at package.json

**Comment by WangXBruc** [comment]
JSENCRYPT_VERSION error. Please  please please fix it soon

**Comment by wufeng87** [comment]
I couldn't figure out why old versions of jsencrypt got this error too?

**Comment by wufeng87** [comment]
@anrananran Which version will encounter this error?

**Comment by lingxia** [comment]
same question as you

**Comment by karan-more-itorix** [comment]
Same issue. Please fix this

**Comment by manav-kodnani** [comment]
Same issue. Please fix this

**Comment by huguoliang1314** [comment]
same question as you, please fix

**Comment by iulo** [comment]
package should export built file in package.json `main` field,  not the source code index.js @travist

**Comment by iulo** [comment]
guys, if you are using yarn, you can add 
```
"resolutions": {
    "jsencrypt": "3.0.0-rc.1"
  }
```

in your package.json, then delete node_modules and yarn.lock, run `yarn install` again to force yarn install `3.0.0-rc.1`version

**Comment by vjkholiya123** [comment]
> just replace `import JSEncrypt from 'jsencrypt'` with `import JSEncrypt from 'jsencrypt/bin/jsencrypt.min.js'`

After doing this this error gets removed but now I am getting `ReferenceError: window is not defined`

**Comment by Red-xiaoshami** [comment]
same question and  "jsencrypt": "^3.0.0-rc.1"

**Comment by sxzz** [comment]
Fixed in https://github.com/travist/jsencrypt/commit/5ff9a81fc18900926440659213ada41a5f62778e, just use latest version.
```
"jsencrypt": "^3.0.1",
```
