### ISSUE TITLE
 sometimes result is short even-length, eg: 254/256

### ISSUE THREAD

**Issue by jordiwang** [travist/jsencrypt#203]
![image](https://user-images.githubusercontent.com/29055881/109385119-6847f400-792c-11eb-9bf0-acc472cbb2db.png)

find that some 254 length result in `rsa.ts` will escape this `h.length & 1` statement, and return a non-standard result

is this might be better?

![image](https://user-images.githubusercontent.com/29055881/109385302-c7f2cf00-792d-11eb-9383-0bf15cf0cd7f.png)

**Comment by travist** [comment]
Fixed in 3.0.3
