### ISSUE TITLE
长文本加密，后端怎么解析？

### ISSUE THREAD

**Issue by zty381309501** [travist/jsencrypt#231]
后端获取到的前端加密信息（使用encryptLong），怎么分段解密？分段的逻辑是什么呢？大佬，麻烦您了。

**Comment by chang0022** [comment]
你应该是使用的这个库？https://github.com/lsxlsxxslxsl/encryptlong

**Comment by zty381309501** [comment]
> 你应该是使用的这个库？https://github.com/lsxlsxxslxsl/encryptlong

确实是这个。大佬知道解密怎么分段吗？

**Comment by chang0022** [comment]
> > 你应该是使用的这个库？https://github.com/lsxlsxxslxsl/encryptlong
> 
> 确实是这个。大佬知道解密怎么分段吗？

原理：https://github.com/travist/jsencrypt/issues/110 可以参考代码。

**Comment by chang0022** [comment]
建议 Close 这个 issue 了。毕竟不是这个库的问题。
