### ISSUE TITLE
ERROR in ./node_modules/jsencrypt/lib/index.js 1:0-40

### ISSUE THREAD

**Issue by ashokram** [travist/jsencrypt#270]
Hi, getting error with the latest version "3.3.0" in React, this is working fine with the previous version 3.2.1

Thank you.

![Error](https://user-images.githubusercontent.com/3068888/198301149-8db59ec8-2608-41a7-af02-410432ac7ef7.png)

**Comment by litt1e-p** [comment]
same error

**Comment by aak1247** [comment]
Please do not make breaking change in patch version 😥

**Comment by jdsalasca** [comment]
Hi everyone I have find as a temporary solution is to change the version of jsencrypt to   "jsencrypt": "^3.0.0-rc.1",  that can fix the problem

The problem is because of webpack5 have change the way it builds the project dependencies. 

Have a good day

**Comment by promise96319** [comment]
This config will solve the problem.

``` ts
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.m?js$/,
        resolve: {
          fullySpecified: false, // disable the behaviour
        },
      },
    ],
  },
};
```

When package.json contains a field of "type" with the value of "module" , webpack requires a full path(including the file extension, like .js/.mjs)，otherwise webpack would fail the compiling with a Module not found error. Setting fullySpecified to false disables this behavior.

You can check it at [Webpack docs](https://webpack.js.org/configuration/module/#resolvefullyspecified).

**Comment by jonasvoelcker** [comment]
For me this just looks like a small patch and no solution, additionally we don't have an appropriate loader for this config.
The problem still exists with the new version 3.3.1 ;)

**Comment by whitetrefoil** [comment]
It seems the tsconfig not set to output an ESM. So the generated JS files import without the ".js" extname.

**Comment by wxf1024** [comment]
NOT A GOOD PRACTICE:

just
``` js
import 'jsencrypt/bin/jsencrypt'
````
and you have a global JSEncrypt.  
using it anywhere:
``` js
const enc = new JSEncrypt()
```

**Comment by dj49846917** [comment]
How to solve this problem in umijs and how to configure it on chainWebpack！

**Comment by travist** [comment]
Please try 3.3.2 and see if it fixes this issue.
