### ISSUE TITLE
Fail to import JSEncrypt module

### ISSUE THREAD

**Issue by valebearzotti** [travist/jsencrypt#273]
Hello. I recently installed the JSEncrypt library running `npm install --save jsencrypt` on my React.js project. I would like to import it and use it in a function but I keep getting the following error:

```
ERROR in ./node_modules/jsencrypt/lib/index.js 1:0-40
Module not found: Error: Can't resolve './JSEncrypt' in 'C:\etcetcpathtomyproject\node_modules\jsencrypt\lib'
Did you mean 'JSEncrypt.js'?
BREAKING CHANGE: The request './JSEncrypt' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Any ideas on why this is caused? I'm trying to import the module using `import { JSEncrypt } from 'jsencrypt` and I also tried without the curly braces.

**Comment by kun1984** [comment]
downgraded the version  v3.2.1

**Comment by BleileJustin** [comment]
bump

**Comment by wywolf** [comment]
3.2.1 版本还是报错呢?

**Comment by NishargShah** [comment]
This is a temporary solution but worth it.

```
npm uninstall jsencrypt
npm install jsencrypt@3.0.0-rc.1
```

**Comment by travist** [comment]
Please try version 3.3.2

**Comment by XongMer** [comment]
jekins 构建项目的时候报错 ，更换了jsEncrypt的版本 也不行 有没有朋友知道的啊
10:53:19 Error: [vite]: Rollup failed to resolve import "JSEncrypt" from "src/utils/jsencrypt.ts".
10:53:19 This is most likely unintended because it can break your application at runtime.
10:53:19 If you do want to externalize this module explicitly add it to
10:53:19 `build.rollupOptions.external`

**Comment by skys215** [comment]
> This is a temporary solution but worth it.
> 
> ```
> npm uninstall jsencrypt
> npm install jsencrypt@3.0.0-rc.1
> ```

Got `navigator is not defined` for me.

**Comment by saozhu2333** [comment]
> > 这是一个临时解决方案，但值得。
> > ```
> > npm uninstall jsencrypt
> > npm install jsencrypt@3.0.0-rc.1
> > ```
> 
> 为我而来。`navigator is not defined`

I used him but still reported an error
