### ISSUE TITLE
jsencrypt does not like node.js - or the other way around. 

### ISSUE THREAD

**Issue by trasherdk** [travist/jsencrypt#278]
`filename.js`
```js
// import * as JSEncrypt from 'jsencrypt' // ReferenceError: window is not defined
// import JSEncrypt from 'jsencrypt' // SyntaxError: The requested module 'jsencrypt' does not provide an export named 'default'
// import { default as JSEncrypt } from 'jsencrypt' // SyntaxError: The requested module 'jsencrypt' does not provide an export named 'default'
// import { JSEncrypt } from 'jsencrypt' // SyntaxError: The requested module 'jsencrypt' does not provide an export named 'JSEncrypt'
// const JSEncrypt = await import('jsencrypt') // ReferenceError: window is not defined
import { readFileSync } from 'fs'
import path, { resolve } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const pubpem = readFileSync(resolve(__dirname, '../ca/server-crt.pem')).toString('utf8')
const keypem = readFileSync(resolve(__dirname, '../ca/server-key.pem')).toString('utf8')

const message = 'Secret message to encrypt'

const encrypt = new JSEncrypt()
encrypt.setPublicKey(pubpem)
const encrypted = encrypt.encrypt(message)


const decrypt = new JSEncrypt()
decrypt.setPrivateKey(keypem)
const uncrypted = decrypt.decrypt(encrypted)

if (message === uncrypted) {
  console.log(`All good: ${message} === ${uncrypted}`)
} else {
  console.error(`Not so good: ${message} !== ${uncrypted}`)
}
```

**Comment by milaabl** [comment]
Same errors in a React + TS app!!!

**Comment by milaabl** [comment]
Had to move to using a CDN which is very inconvenient. There doesn't seem to be any compatibility with React, as none of the files that /node_modules/jsencrypt contains could have been imported successfully.

**Comment by BleileJustin** [comment]
Bump!
This is extremely irritating. There is no compatibility with react anymore.
![Screenshot 2022-12-10 at 4 00 37 PM](https://user-images.githubusercontent.com/25036525/206879684-d5976619-abdd-44fd-b41f-c0cbf9859b90.png)
![Screenshot 2022-12-10 at 4 00 26 PM](https://user-images.githubusercontent.com/25036525/206879687-d9cb4b5b-8322-49a8-8bf0-246bae4e049f.png)
![Screenshot 2022-12-10 at 4 01 19 PM](https://user-images.githubusercontent.com/25036525/206879690-3753339b-1b9d-4290-a692-b7cc8545a90d.png)
![Screenshot 2022-12-10 at 4 00 55 PM](https://user-images.githubusercontent.com/25036525/206879693-4f415d0c-53be-4c22-aca9-0eb37a6775ad.png)

**Comment by Gusttavo13** [comment]
> Bump! This is extremely irritating. There is no compatibility with react anymore. ![Screenshot 2022-12-10 at 4 00 37 PM](https://user-images.githubusercontent.com/25036525/206879684-d5976619-abdd-44fd-b41f-c0cbf9859b90.png) ![Screenshot 2022-12-10 at 4 00 26 PM](https://user-images.githubusercontent.com/25036525/206879687-d9cb4b5b-8322-49a8-8bf0-246bae4e049f.png) ![Screenshot 2022-12-10 at 4 01 19 PM](https://user-images.githubusercontent.com/25036525/206879690-3753339b-1b9d-4290-a692-b7cc8545a90d.png) ![Screenshot 2022-12-10 at 4 00 55 PM](https://user-images.githubusercontent.com/25036525/206879693-4f415d0c-53be-4c22-aca9-0eb37a6775ad.png)

Same here, Were you able to solve this   @@problem?

**Comment by BleileJustin** [comment]
@Gusttavo13  Unfortunately not. I had to do 
`npm uninstall jsencrypt`

**Comment by jiekechens** [comment]
you can in the jsencrypt.js do  window.JSEncrypt = JSEncrypt;

**Comment by travist** [comment]
Please try version 3.3.2 and see if this issue is resolved.

**Comment by skys215** [comment]
> 

Problem remains for me.
version 3.2.1 is also the same.
