### ISSUE TITLE
Module not found: Error: Can't resolve './JSEncrypt' in....

### ISSUE THREAD

**Issue by faridfauzi-990** [travist/jsencrypt#282]
I found out that **The request './JSEncrypt' failed to resolve ** .

This is node modules file where I only download directly with 'npm i' command.
If I run in windows is okay.
Maybe running in linux environment couldn't succeeded?
But I really need to download manually in the linux environment there. 

![image](https://user-images.githubusercontent.com/71166013/208038485-e3f19eef-c82c-448c-9e42-89ade7f6b30c.png)

**Comment by Geddard** [comment]
Definitely happening with versions above 3.3.0, with a fresh create-react-app installation, hope this gets resolved soon

**Comment by faridfauzi-990** [comment]
cannot resolve

**Comment by faridfauzi-990** [comment]
close
