### ISSUE TITLE
Are there any active maintainers? The bugs are not getting any feedback anymore

### ISSUE THREAD

**Issue by c-plus-plus-equals-c-plus-one** [travist/jsencrypt#284]
There's a breaking bug in the last version of jsencrypt. It no longer works with React and VueJS. I guess it doesn't work with NPM (at lieast ES6 imports) anymore. #273

**Comment by NishargShah** [comment]
This is a temporary solution but worth it.

```
npm uninstall jsencrypt
npm install jsencrypt@3.0.0-rc.1
```

**Comment by jiekechens** [comment]
thanks bro
