### ISSUE TITLE
Module not found: Error: Can't resolve './lib/jsbn/base64' in 'C:\Users\jackdu\Documents\Project\lowcode-admin\node_modules\jsencrypt\lib'

### ISSUE THREAD

**Issue by dj49846917** [travist/jsencrypt#287]
How to solve this problem in umijs and how to configure it on chainWebpack
![WeChat Screenshot_20230206124555](https://user-images.githubusercontent.com/30486590/216885797-d1982661-1c95-4511-8c95-3ceb93f59ba6.png)

**Comment by dj49846917** [comment]
version: 3.3.1

**Comment by jiekechens** [comment]
别安装 看下载源码文件那样common 引入形式行不行

**Comment by travist** [comment]
Try using version 3.3.2 and see if it fixes this problem.
