### ISSUE TITLE
Decrypted result has wrong encoding

### ISSUE THREAD

**Issue by StigoSvK** [travist/jsencrypt#288]
Hi. When I try to decrypt ciphertext which was encrypted by JSEncrypt, everything works just fine. But when I try to decrypt data (array buffer) which was encrypted in Swift (using native crypto API), I'm receiving result in strange encoding like this:

`$P|2孭b坵ₛ꘴3Wⴅ|ᎁ­쯎`

Encrypted data came as array buffer from protobuf message which I just encoded to base64 using:

```
function arrayBufferToBase64(message: Uint8Array) {
  return window.btoa(
    message.reduce(function (data, byte) {
      return data + String.fromCharCode(byte);
    }, ''),
  );
}
```

Could you figure out what am I doing wrong? Thanks

**Comment by StigoSvK** [comment]
Update. After switching to using only the web crypto API that works with ArrayBuffer, I no longer have this issue. Maybe consider to support Array Buffer by default.

**Comment by anrananran** [comment]
> web crypto API

Hi, I have the same issue, Can you share your example code how to decrypt ArrayBuffer ? thx
