### ISSUE TITLE
@3.3.2 linux public  Rollup failed to resolve import 

### ISSUE THREAD

**Issue by saozhu2333** [travist/jsencrypt#311]
Packaging in Linux can cause issues
vite+vue3+ts
![ff86ca58e6ed0e3b840a30034a4409df](https://github.com/travist/jsencrypt/assets/52821281/e5b16ad6-60a2-4514-ac13-eded9e47fb8e)

**Comment by saozhu2333** [comment]
I did not use it correctly. The name generated by import is in uppercase letters, which is different from the name in node.modules

**Comment by saozhu2333** [comment]
I did not use it correctly. The name generated by import is in uppercase letters, which is different from the name in node.modules

**Comment by suka233** [comment]
Same issue here，use ` import JSEncrypt from 'jsencrypt' ` instead of `import JSEncrypt from 'JSEncrypt' `
