### ISSUE TITLE
client side encrypt, server side decrypt node.js ursa

### ISSUE THREAD

**Issue by gurumelo** [travist/jsencrypt#39]
Hello, i try to do this:

client side
var crypt = new JSEncrypt();
crypt.setKey('-----BEGIN PUBLIC KEY-----YOUR PUBLIC KEY-----END PUBLIC KEY-----'); //You can use also setPrivateKey and setPublicKey, they are
both alias to setKey

//Eventhough the methods are called setPublicKey and setPrivateKey, remember
//that they are only alias to setKey, so you can pass them both a private or
//a public openssl key, just remember that setting a public key allows you to only encrypt.

var text = 'test';
// Encrypt the data with the public key.
var enc = crypt.encrypt(text);
alert(enc);

And the server side:

'use strict';

var fs = require('fs')
, ursa = require('ursa')
, crt
, key
, msg
;

key = ursa.createPrivateKey(fs.readFileSync('./rsapriv.pem'));

msg = 'oDdwc6sYZz1FxpFr/ZumS2rrgkUN38raevlj4iNLDZg6JcQkxB9ARXnhd+Jljx37xgoVcQ+rmDQZQLMVjsFOoSBGjuR+uDnY3V8u+8OQpcODMgNU1nFaqrgt34s904Djf6a9kxqO33CZWg2rCjM+XzA2SlfcH66CiBMhW0
CeB+pPxLN0Hx+pmSzla7+J1B3DG8/Nan9LltzZ8/RdHwks2icWylCbUvRadQamQDUKjhKfPSH4ITLAw9QjJy+qT+GyXvv9JDRBI2WocIcADDRqkJScpw20pJKEz6WC8cs8stSpNrSOebDIj3tnquo0yqa4Ok8AXzakk4lndtBZqPI
JBA==';

console.log('Decrypt with Private');
msg = key.decrypt(msg, 'base64', 'utf8');
console.log(msg);

Error:
return encodeBuffer(rsa.privateDecrypt(buf, padding), outEncoding);
^
Error: error:0407A079:rsa routines:RSA_padding_check_PKCS1_OAEP:oaep decoding error
at Object.decrypt (/home/mari/node/jsencrypt/node_modules/ursa/lib/ursa.js:291:33)
at Object. (/home/mari/node/jsencrypt/server2.js:23:11)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3

thank you

**Comment by Jeija** [comment]
I had the same issue.
Setting the correct padding type for decryption fixed it for me:
Use `ursa.RSA_PKCS1_PADDING` with `key.decrypt(buf, bufEncoding, outEncoding, padding)`

```JavaScript
msg = key.decrypt(msg, 'base64', 'utf8');
```
becomes
```JavaScript
msg = key.decrypt(msg, 'base64', 'utf8', ursa.RSA_PKCS1_PADDING);
```

**Comment by Latrell** [comment]
I have also experienced similar problems, the library can not support RSA_OAEP_PADDING it?

**Comment by kaushik-evani** [comment]
I had the same problem. My client was an android app. I was encrypting in android and decrypting it in node using ursa. i tried ursa.RSA_PKCS1_PADDING and ursa.RSA_PKCS1_OAEP_PADDING. I tried changing the padding type in android as well which did not work. As it turned out, android was not using any padding and by default ursa was checking for padding. After going through the ursa library, I found that you can even use ursa.RSA_NO_PADDING which did the trick. Dunno if this is still useful to you. But this thread is what led me to my solution. So thanks a lot!

**Comment by sfsw** [comment]
no need to use ursa module anymore, just node crypto module!

**Comment by suibobuzhuliu** [comment]
I had the same problem. How to set the padding type?

**Comment by gurumelo** [comment]
https://www.npmjs.com/package/jsdecrypt
