### ISSUE TITLE
Encrypting text with public key generated in a different browser returns false

### ISSUE THREAD

**Issue by joosthoutbeckers** [travist/jsencrypt#40]
I am trying to encrypt data with a public key from someone else received out of my database but all I get is "false". I checked if the public key I got from the database was the same as the one generated by the different browser and they match.
Code:

    var crypt = new JSEncrypt();
    crypt.setPublicKey($("#rkey").val());
    var password = crypt.encrypt(pass);

(rkey is the recipients public key key gained from the database and pass is a password generated in the browser)

**Comment by vncastanheira** [comment]
I

**Comment by zoloft** [comment]
can you provide the public key?

**Comment by joosthoutbeckers** [comment]
Thank you for your response,

Somehow (no clue how though) the error is gone now. Thank you for
responding though!

Best regards,

Joost Houtbeckers

**Comment by vncastanheira** [comment]
I can. I tried to use a public key created with `RSACryptoServiceProvider`, a `.NET` class. It generates a XML string that I sent to my view and used that as the public key.
Since they are both RSA implementation, I thought that it would work.

**Comment by zoloft** [comment]
@vncastanheira please open a new bug for this and include the generated RSA Key. Closing this.
