### ISSUE TITLE
The encrypted string is always not the same

### ISSUE THREAD

**Issue by AndyShad** [travist/jsencrypt#43]
Hello,Why the encrypted string is always not the same even I didn't change the public key.
plz help me.

**Comment by AndyShad** [comment]
E,  What I mean is how can I get the same encrypted string,thank you.

**Comment by AndyShad** [comment]
I got it.Because of Random Padding.
The RSA encryption encrypts message padded with '0's and and a string of random bit. In the process, the random string is "hidden" in the ciphertext by cryptographic hashing and XORing. On decryption, the RSA decryption recovers the random string from the ciphertext and use it to recover message. This is why you get different result with openssl rsautl for the same text message.

**Comment by zoloft** [comment]
So you did everything on your own, good! XD

**Comment by qfwfqf** [comment]
> Hello,Why the encrypted string is always not the same even I didn't change the public key.

how did u solve this? that i have got the same problem! pls help me
