### ISSUE TITLE
node-rsa can't decrypt

### ISSUE THREAD

**Issue by Baccanno** [travist/jsencrypt#46]
Probably having the same issue as #39 but my message error is more like ""Error during decryption (probably incorrect key).""

It works well on local.

**Comment by Baccanno** [comment]
So yes it's the same issue, this works. Maybe consider switching to PKCS1_OAEP padding by default or give the possibility to use one or another.

```javascript
	privKey = new NodeRSA( data, 'pkcs1-private-pem', {
		'encryptionScheme': 'pkcs1'
	})
```

**Comment by newnok6** [comment]
thank a lot !!!, I've used 3 hours to solve this problem

**Comment by ajira86** [comment]
:+1:

**Comment by rajkumar-surnar** [comment]
Thanks Baccanno ...!!!
