### ISSUE TITLE
Do not include minified file in bower.json

### ISSUE THREAD

**Issue by jansensan** [travist/jsencrypt#49]
As per [Bower specs](http://bower.io/docs/creating-packages/#main), minified files should not be used in the `main` property.

    "main": "bin/jsencrypt.js"

is what should be used instead.

**Comment by afaubert** [comment]
+1

**Comment by jansensan** [comment]
Submitted PR: https://github.com/travist/jsencrypt/pull/50

**Comment by zoloft** [comment]
P.S. Thank you for submitting it in the develop branch, will be easier when I get some time to work on it!
