### ISSUE TITLE
Math.random on V8 not random enough

### ISSUE THREAD

**Issue by pmontrasio** [travist/jsencrypt#57]
I just read [TIFU by using Math.random()](https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d) (discussion on HN at https://news.ycombinator.com/item?id=10598065). TL;DR this is what ```Math.random``` yields on Firefox

![firefox random 500x140](https://cloud.githubusercontent.com/assets/47483/11318185/8f939164-9047-11e5-9654-4106de89c315.png)

and this is what it yields on V8

![v8 random 500x140](https://cloud.githubusercontent.com/assets/47483/11318186/9b4d1e62-9047-11e5-96a4-56cf4862a018.png)

The author suggests using ```crypto.getRandomValues``` in the browser. That populates a typed array with random values. Example:

    > var random_int32 = new Uint32Array(5);
    > crypto.getRandomValues(random_int32)
    [3893288831, 502897280, 4154045839, 415033321, 3522955257]

https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues

**Comment by jalada** [comment]
As far as I know, JSEncrypt already uses `crypto.getRandomValues` when it can.

JSEncrypt uses JSBN behind the scenes, and that has a PRNG that first tries `getRandomValues`. If that's not available, it uses mouse entropy. If it runs out of mouse entropy then yes, it falls back to `Math.random`.

https://github.com/travist/jsencrypt/blob/master/lib/jsbn/rng.js

**Comment by zoloft** [comment]
@jalada exactly, thank you :)

**Comment by pmontrasio** [comment]
I'm afraid I didn't check the code well enough. Sorry for wasting your time.

**Comment by jalada** [comment]
Not a problem @pmontrasio, I actually came here to double check JSEncrypt because of the same blog post.

**Comment by zoloft** [comment]
@pmontrasio & @jalada P.S. kudos to @ctso for his work in travist/jsencrypt#6
