### ISSUE TITLE
Decrypt with public key

### ISSUE THREAD

**Issue by kamillis** [travist/jsencrypt#62]
Hello, is there any way to decrypt text using public key instead a private key? I would like to encrypt message on server using server's private key and I would like to decrypt it in browser using public key.

**Comment by chris03** [comment]
You should read about how [Publickey cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography) works.

**Comment by murkle** [comment]
http://security.stackexchange.com/questions/9957/can-i-use-a-private-key-as-a-public-key-and-vice-versa
"You don't need to publish the private key at all - RSA is a trapdoor permutation which means:
If you encrypt with a public key, you can decrypt with the private key.
If you encrypt with a private key, you can decrypt with a public key."

**Comment by murkle** [comment]
Working demo using Tom Wu's library:

http://ats.oka.nu/titaniumcore/js/crypto/RSA.sample2.html?pr=T3ser7WdHa83DcMujTvulOLUi5ka8sGPYknHheupz1pFNLPP5Mxbk0clm6p71Lj7i7Wg4Yj2kHOOyaFzfglgUM2zsRH4ZuSKzjSNAOMhxxstzcldj3J9e6lzmDiENUJVEKqzQ0QpCWh85xx4YmHqoeoXw&pu=ODIz4KKpjgEK7xxs2Q0buHtPyW53KlpGxaRMTpNm4H83F5rq3DkaLEN6GM7JOU7ELUDl2iRnygBvASjEm4edNCexaRki3Jpdoo4q4zxaogBgpdk&e=65537&pa=1&dum=he
