### ISSUE TITLE
about npm support

### ISSUE THREAD

**Issue by lmnsg** [travist/jsencrypt#64]
I see, you had publish done the library to npm.
But, the latest version still have not the main attribute, so, it is not available when I require it in my application.
however I can use `require('jsencrypt/src/jsencrypt.js')`, but..... you know, I am very lazy!

so, would you please republish a new version to fix it?
Thank you!

**Comment by fresheneesz** [comment]
@travist I see the version on NPM is 2 years old. Is it out of date at this point? I would suggest adding a note about how to install via npm in the readme, but if its out of date, it should be updated before adding that note.

**Comment by fresheneesz** [comment]
Also, I definitely agree with Imnsg, I got pretty confused that I couldn't require("jsencrypt") - it gave me an error that it couldn't find it until I used the require string imnsg wrote

**Comment by zoloft** [comment]
@travist can you address this? It should be a mere version upgrade to the package.json file as the main file has already been specified (PR #63)

**Comment by travist** [comment]
Yep, I will fix and push up a new version today.

**Comment by zoloft** [comment]
Great, thank you!

**Comment by travist** [comment]
Just pushed up the version 2.2.0 to npm. Let me know if that works for you guys.
