### ISSUE TITLE
jsencrypt.js missing on server (so example doesn't work)

### ISSUE THREAD

**Issue by murkle** [travist/jsencrypt#74]
This file is missing on your server:
http://travistidwell.com/bin/jsencrypt.js

**Comment by vipersec** [comment]
@murkle are you talking about this?
http://travistidwell.com/jsencrypt/bin/jsencrypt.js

**Comment by murkle** [comment]
If you go here (as linked from https://github.com/travist/jsencrypt)
http://travistidwell.com/jsencrypt/example.html
then it looks for
http://travistidwell.com/bin/jsencrypt.js 

(so either a mistake in the html, or the file is in the wrong place)

**Comment by vipersec** [comment]
@murkle Yes indeed, however if you want to try it you can download and run it locally (after you link the jsencrypt.js)

**Comment by zoloft** [comment]
@travist need to fix this

**Comment by travist** [comment]
Thanks... This page is now fixed.
