### ISSUE TITLE
Max 501 chars

### ISSUE THREAD

**Issue by fluctuate** [travist/jsencrypt#88]
Hi,

i started to use this lib just this week, encryption and decryption work fine, but if i use an original message with more than 501 chars, then decryption fails.
I generate private/public keys by "openssl" on linux console, keys in 4096 bit.
I created my keys as follow:
private: openssl genrsa -out  priv_key.pem  4096
public: openssl rsa -pubout -in  priv_key.pem   -out  pub_key.pem

So, do i've done something wrong?

it's very strange because until 501 chars all works fine.

Thank you,
  Fluc

**Comment by zoloft** [comment]
The length of the message you can encrypt/decrypt is bound to the length of the key you are using. [Read more here :)](http://stackoverflow.com/questions/5866129/rsa-encryption-problem-size-of-payload-data)
